name: app
description: "GNext logistic application"

publish_to: 'none'

version: 4.8.1+6.8

environment:
  sdk: '>=3.3.0 <5.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Responsiveness
  responsive_sizer: ^3.3.0+1
  cupertino_icons: ^1.0.2
  pinput: ^5.0.1

  # Internationalization
  intl: ^0.20.2

  # Firebase
  firebase_core: ^3.5.0
  firebase_auth: ^5.1.1
  firebase_messaging: ^15.0.2
  firebase_crashlytics: ^4.0.2

  # Networking
  dio: ^5.3.0
  retrofit: ^4.5.0
  json_annotation: ^4.8.1

  # State management
  flutter_bloc: ^9.1.1
  provider: ^6.0.5

  # UI components & utilities
  flutter_slider_drawer: ^3.0.2
  buttons_tabbar: ^1.3.8
  motion_toast: ^2.8.0
  animated_custom_dropdown: ^3.0.0
  bottom_picker: ^3.2.1

  # Media & File handling
  image_picker: ^1.0.7
  file_picker: ^10.2.0
  flutter_file_downloader: ^2.1.0
  video_player: ^2.8.3
  url_launcher: ^6.2.5
  story: ^1.1.0
  audio_waveforms: ^1.0.5
  flutter_paypal_payment: ^1.0.6

  # Location & Device info
  geocoding: ^4.0.0
  socket_io_client: ^3.1.2
  device_info_plus: ^11.5.0

  # Notifications & Permissions
  flutter_local_notifications: ^19.3.0
  permission_handler: ^12.0.1

  # Storage & Conversion
  shared_preferences: ^2.2.2
  currency_converter: ^2.0.0
  in_app_purchase: ^3.2.0
  change_app_package_name: ^1.2.0

  # Voice messages
  syncfusion_flutter_sliders: ^25.2.7
  voice_message_package: ^2.2.0
  flutter_chat_bubble: ^2.0.2
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.6.2
  retrofit_generator: ^9.0.0
  icons_launcher: ^3.0.1

dependency_overrides:
  intl: ^0.20.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

icons_launcher:
  image_path: "assets/icon.png"
  platforms:
    android:
      image_path: 'assets/icon_border.png'
      adaptive_background_image: 'assets/background.png'
      adaptive_foreground_image: 'assets/icon_foregraund.png'
      adaptive_round_image: 'assets/icon_round.png'
      enable: true
    ios:
      enable: true

# Конфигурация flutter_intl (перенесена вне зависимостей)
flutter_intl:
  enabled: true
  main_locale: ru